# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.



#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`


In [169]:
import numpy as np


#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`



In [170]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`



In [171]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`


In [172]:
val_vector = np.arange(10,50)
print(val_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`


In [173]:
three_by_three = np.arange(0,9).reshape((3,3))
print(three_by_three)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`



In [174]:
non_zero_ind = np.array([1,2,0,0,4,0]).nonzero()
print(non_zero_ind)

(array([0, 1, 4], dtype=int64),)


#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`



In [175]:
three_by_three_ident_matrix = np.eye(3)
print(three_by_three_ident_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`



In [185]:
three_three_random = np.random.random((3,3,3))
print(three_three_random)

[[[0.56831168 0.20473234 0.38043649]
  [0.11602386 0.95809687 0.24330586]
  [0.1469943  0.49748665 0.55566361]]

 [[0.11663956 0.57160151 0.65021782]
  [0.6551842  0.83219027 0.48694003]
  [0.45449626 0.95070485 0.72348807]]

 [[0.80805857 0.26227537 0.25921699]
  [0.22166286 0.02183191 0.87874234]
  [0.65494569 0.85484881 0.51244642]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`


In [177]:
random_matrix = np.random.randint(1,100,(10,10))
print(random_matrix)
print(f"\n----\nMinimum value: {np.min(random_matrix)}")
print(f"Maximum value: {np.max(random_matrix)}")

[[49 56 36 99 66 45 35 82 94 36]
 [38 21 59 38 57 78 33 86  2 94]
 [40 79 64 28 97 14 36 71 15 16]
 [96 81 38  9  3 14 24 85 46 55]
 [56 40 58 65 47 77 77 95 19 93]
 [76 16 24 30 42 72 50  3 75 23]
 [14 62 48 17 53 61 23 20 52 77]
 [47  7 58 92 82 20 84 97 93 24]
 [14 67 34 64 12 62 98 85 95 88]
 [90 99 31 55 40 38 34 20 57 47]]

----
Minimum value: 2
Maximum value: 99


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`



In [205]:
this_vector = np.random.random(30) 
print(this_vector)
print(f"---\nMean: {np.mean(this_vector)}")

[0.81898156 0.66850092 0.41462881 0.34431822 0.48918997 0.9284449
 0.79355357 0.04848427 0.16342303 0.60421712 0.36636738 0.73930765
 0.90780402 0.51916725 0.26904612 0.21956585 0.88339953 0.95882051
 0.49271666 0.15580771 0.65015543 0.74182496 0.63185154 0.29914552
 0.69632153 0.54103242 0.38588184 0.17566223 0.9696253  0.18348022]
---
Mean: 0.5353575352521788


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`



In [200]:
print(np.diag([1,2,3,4],-1))



[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`



In [180]:
random_matrix = np.random.randint(1,20,(5,5))
print("- Random -")
print(random_matrix)
print("- Normalized -")
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix) 
print(normalized_matrix)
print("- - -")
print(f"Mean: {round(np.mean(normalized_vector), 8)}, StandDev: {round(np.std(normalized_vector), 8)}")


- Random -
[[ 2 17 15 13  8]
 [14  7 13 11 13]
 [15 17  1 14 19]
 [17 14  6  3 16]
 [ 3 14  3  5  1]]
- Normalized -
[[-1.4664097   1.13976868  0.79227823  0.44478778 -0.42393835]
 [ 0.618533   -0.59768358  0.44478778  0.09729733  0.44478778]
 [ 0.79227823  1.13976868 -1.64015493  0.618533    1.48725913]
 [ 1.13976868  0.618533   -0.7714288  -1.29266448  0.96602345]
 [-1.29266448  0.618533   -1.29266448 -0.94517403 -1.64015493]]
- - -
Mean: -0.0, StandDev: 1.0


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`



In [181]:
array1 = np.random.randint(1,20,20)
array2 = np.random.randint(1,20,20)
print(array1)
print(array2)
print(np.intersect1d(array1, array2))

[12  4  7 15  8 17 14 14 10  2 12 10 12  3 13  5 19 16  3 12]
[17 12  3 11 12 16 16  7  1  1 17 19  5 11 16 13  3  6 10  1]
[ 3  5  7 10 12 13 16 17 19]


#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`



In [182]:
print(np.sort(np.random.randint(1,25,10)))

[ 3  4  5  5 11 14 14 18 19 23]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`



In [210]:
this_vector = np.random.randint(1,50,10)
print(f"Vector: {this_vector}, with maximum value of {this_vector[np.argmax(this_vector)]} at index {np.argmax(this_vector)}")


Vector: [27 31  9 17 34 31 21 47 21  7], with maximum value of 47 at index 7


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`



In [211]:
random_matrix = np.random.randint(1,50,(5, 5))
print("Original matrix:")
print(random_matrix)
print("\nSubtract the mean of each row:")
substr_matrix = random_matrix - random_matrix.mean(axis=1, keepdims=True)
print(substr_matrix)

Original matrix:
[[15 42 38 27 30]
 [14  7 48  4 17]
 [25 46 17 36 34]
 [12 46  6  3 30]
 [38 25 47 45 40]]

Subtract the mean of each row:
[[-15.4  11.6   7.6  -3.4  -0.4]
 [ -4.  -11.   30.  -14.   -1. ]
 [ -6.6  14.4 -14.6   4.4   2.4]
 [ -7.4  26.6 -13.4 -16.4  10.6]
 [ -1.  -14.    8.    6.    1. ]]


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`



In [215]:
Z = 100000
n = 5
random_array = np.arange(Z)

np.random.shuffle(random_array)
print(random_array)
# argsort WORKS! 
n_largest_indeces = np.argsort(random_array)[Z-n:]
print(f"indeces of the n highest numbers starting with the smallest of these: {n_largest_indeces}")
for _ in n_largest_indeces:
    print(random_array[_])



[27290 42862 21012 ... 16403 22158 92149]
indeces of the n highest numbers starting with the smallest of these: [71226 67996 31952  9582   531]
99995
99996
99997
99998
99999


In [216]:
# argpartition
Z = 10000
n = 5
random_array = np.arange(Z)
np.random.shuffle(random_array)

print(np.argpartition(random_array,Z-n))
print(np.argpartition(random_array,Z-n)[-n:])
print(random_array[np.argpartition(random_array,Z-n)[-n:]])


[3736 9999    2 ... 9136 9978 2964]
[6622 2706 9136 9978 2964]
[9995 9996 9997 9999 9998]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [217]:
random_matrix = np.random.randint(1,10,(5,3))
print(random_matrix)
print("----")
print(np.where(random_matrix > 4, random_matrix**2, random_matrix))

[[6 2 3]
 [5 6 2]
 [5 8 1]
 [9 4 9]
 [1 7 4]]
----
[[36  2  3]
 [25 36  2]
 [25 64  1]
 [81  4 81]
 [ 1 49  4]]
